kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: python-ptds
<<<<<<< HEAD:k8s/app/python-ptds-deployment.yaml
  namespace: production-namespace
=======
  namespace: production
>>>>>>> canary:k8s/helm/app/python-ptds-deployment.yaml
spec:
  replicas: 3
  template:
    metadata:
      name: python-ptds
      labels:
        app: python-ptds
        type: {{ .Values.type }}
    spec:
      containers:
      - name: python-ptds-image
        image: gmurra11/python-ptds
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ptds
            port: 5000
          timeoutSeconds: 5
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - name: python-ptds
          containerPort: 80
