kind: Service
apiVersion: v1
metadata:
  name: python-ptds-service
  namespace: production
  labels:
    app: python-ptds
    type: {{ .Values.type }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: python-ptds
