kind: Service
apiVersion: v1
metadata:
  name: python-ptds-service
<<<<<<< HEAD:k8s/app/python-ptds-services.yaml
  namespace: production-namespace
=======
  namespace: production
>>>>>>> canary:k8s/helm/app/python-ptds-services.yaml
  labels:
    app: python-ptds
    type: {{ .Values.type }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: python-ptds
